# Auto-generated monolith for the DeepSeek-V4 Mini inference pipeline.
# Source package: inference/
# Generated by concatenating the inference modules in dependency order.

from __future__ import annotations



# ==============================================================================
# inference/inference_config.py
# ==============================================================================

from dataclasses import dataclass
from typing import Optional


@dataclass
class InferenceConfig:
    max_new_tokens: int = 128

    use_cache: bool = True
    cache_mode: str = "audit"
    cache_dtype: str = "fp32"
    device: str = "auto"

    # Generation
    do_sample: bool = True
    temperature: float = 1.0
    top_k: Optional[int] = None
    top_p: Optional[float] = None
    repetition_penalty: Optional[float] = None

    eos_token_id: Optional[int] = None
    pad_token_id: Optional[int] = None

    # Cache behavior
    deepseek_prefill_mode: str = "parallel"
    deepseek_cache_population: str = "layer_projection_real"
    validate_deepseek_cache_equivalence: bool = False
    local_window_size: Optional[int] = None
    max_cache_length: Optional[int] = None
    compress_on_block_ready: bool = True

    # MTP-assisted diagnostics/draft decoding
    use_mtp_draft: bool = False
    mtp_accept_mode: str = "greedy"
    max_mtp_draft_tokens: Optional[int] = None

    # Debug
    return_cache_stats: bool = False
    validate_cache_shapes: bool = True

    # Current v1 keeps generation correct by full-context recomputation while
    # maintaining explicit DeepSeek-style caches for inspection.
    fallback_to_full_forward: bool = True

    def validate(self) -> None:
        if self.max_new_tokens < 0:
            raise ValueError(f"max_new_tokens must be >= 0, got {self.max_new_tokens}")

        if self.temperature <= 0:
            raise ValueError(f"temperature must be > 0, got {self.temperature}")

        if self.top_k is not None and self.top_k <= 0:
            raise ValueError(f"top_k must be > 0 when provided, got {self.top_k}")

        if self.top_p is not None and not (0 < self.top_p <= 1):
            raise ValueError(f"top_p must satisfy 0 < top_p <= 1, got {self.top_p}")

        if self.repetition_penalty is not None and self.repetition_penalty <= 0:
            raise ValueError(
                "repetition_penalty must be > 0 when provided, "
                f"got {self.repetition_penalty}"
            )

        if self.cache_dtype not in {"fp32", "bf16", "fp16"}:
            raise ValueError(f"cache_dtype must be one of {{'fp32','bf16','fp16'}}, got {self.cache_dtype}")

        if self.cache_mode not in {"audit", "mha_decode", "deepseek_decode"}:
            raise ValueError(
                "cache_mode must be one of {'audit','mha_decode','deepseek_decode'}, "
                f"got {self.cache_mode!r}"
            )

        if self.deepseek_prefill_mode not in {"parallel", "sequential_debug"}:
            raise ValueError(
                "deepseek_prefill_mode must be one of {'parallel','sequential_debug'}, "
                f"got {self.deepseek_prefill_mode!r}"
            )

        if self.deepseek_cache_population not in {"layer_projection_real", "embedding_proxy_debug"}:
            raise ValueError(
                "deepseek_cache_population must be one of "
                "{'layer_projection_real','embedding_proxy_debug'}, "
                f"got {self.deepseek_cache_population!r}"
            )

        if self.local_window_size is not None and self.local_window_size <= 0:
            raise ValueError(
                f"local_window_size must be > 0 when provided, got {self.local_window_size}"
            )

        if self.max_cache_length is not None and self.max_cache_length <= 0:
            raise ValueError(
                f"max_cache_length must be > 0 when provided, got {self.max_cache_length}"
            )

        if self.max_mtp_draft_tokens is not None and self.max_mtp_draft_tokens <= 0:
            raise ValueError(
                "max_mtp_draft_tokens must be > 0 when provided, "
                f"got {self.max_mtp_draft_tokens}"
            )

        if self.mtp_accept_mode not in {"greedy", "match_main"}:
            raise ValueError(
                "mtp_accept_mode must be one of {'greedy','match_main'}, "
                f"got {self.mtp_accept_mode!r}"
            )


# ==============================================================================
# inference/cache_utils.py
# ==============================================================================

from typing import Any, Optional

import torch


DTYPE_MAP = {
    "fp32": torch.float32,
    "bf16": torch.bfloat16,
    "fp16": torch.float16,
}


def resolve_cache_dtype(cache_dtype: str | torch.dtype) -> torch.dtype:
    if isinstance(cache_dtype, torch.dtype):
        return cache_dtype
    if cache_dtype not in DTYPE_MAP:
        raise ValueError(f"Unsupported cache dtype {cache_dtype!r}")
    return DTYPE_MAP[cache_dtype]


def resolve_device(model: torch.nn.Module, device: str | torch.device = "auto") -> torch.device:
    if isinstance(device, torch.device):
        return device
    if device != "auto":
        return torch.device(device)
    try:
        return next(model.parameters()).device
    except StopIteration:
        return torch.device("cuda" if torch.cuda.is_available() else "cpu")


def tensor_memory_bytes(tensor: Optional[torch.Tensor]) -> int:
    if tensor is None:
        return 0
    return int(tensor.numel() * tensor.element_size())


def tensors_memory_bytes(*tensors: Optional[torch.Tensor]) -> int:
    return sum(tensor_memory_bytes(tensor) for tensor in tensors)


def concat_optional(
    current: Optional[torch.Tensor],
    new: Optional[torch.Tensor],
    *,
    dim: int,
) -> Optional[torch.Tensor]:
    if new is None:
        return current
    if current is None:
        return new
    return torch.cat([current, new], dim=dim)


def crop_last(tensor: Optional[torch.Tensor], max_length: Optional[int], *, dim: int) -> Optional[torch.Tensor]:
    if tensor is None or max_length is None or tensor.shape[dim] <= max_length:
        return tensor
    index = [slice(None)] * tensor.dim()
    index[dim] = slice(tensor.shape[dim] - max_length, tensor.shape[dim])
    return tensor[tuple(index)]


def move_optional(
    tensor: Optional[torch.Tensor],
    *,
    device: Optional[torch.device] = None,
    dtype: Optional[torch.dtype] = None,
) -> Optional[torch.Tensor]:
    if tensor is None:
        return None
    kwargs: dict[str, Any] = {}
    if device is not None:
        kwargs["device"] = device
    if dtype is not None and torch.is_floating_point(tensor):
        kwargs["dtype"] = dtype
    return tensor.to(**kwargs)


def normalize_position_ids(
    position_ids: Optional[torch.Tensor],
    *,
    batch_size: int,
    seq_len: int,
    start_pos: int = 0,
    device: torch.device,
) -> torch.Tensor:
    if position_ids is None:
        base = torch.arange(start_pos, start_pos + seq_len, device=device, dtype=torch.long)
        return base.unsqueeze(0).expand(batch_size, seq_len)

    position_ids = position_ids.to(device=device, dtype=torch.long)
    if position_ids.dim() == 1:
        if position_ids.numel() != seq_len:
            raise ValueError(
                f"position_ids length must be {seq_len}, got {position_ids.numel()}"
            )
        return position_ids.unsqueeze(0).expand(batch_size, seq_len)

    if position_ids.shape != (batch_size, seq_len):
        raise ValueError(
            f"position_ids must have shape {(batch_size, seq_len)} or [{seq_len}], "
            f"got {tuple(position_ids.shape)}"
        )
    return position_ids


def context_window_for_model(model: torch.nn.Module, max_cache_length: Optional[int] = None) -> int:
    model_max = int(getattr(getattr(model, "config", None), "max_seq_len", 0) or 0)
    if max_cache_length is None:
        return model_max if model_max > 0 else 2**30
    if model_max <= 0:
        return int(max_cache_length)
    return min(int(max_cache_length), model_max)


def encode_prompt(prompt: str | list[int] | torch.Tensor, tokenizer: Optional[Any] = None) -> torch.Tensor:
    if torch.is_tensor(prompt):
        ids = prompt.long()
        return ids.unsqueeze(0) if ids.dim() == 1 else ids

    if isinstance(prompt, str):
        if tokenizer is None:
            raise ValueError("A tokenizer is required when prompt is a string.")
        encoded = tokenizer.encode(prompt)
        if hasattr(encoded, "ids"):
            encoded = encoded.ids
        return torch.tensor([list(encoded)], dtype=torch.long)

    return torch.tensor([list(prompt)], dtype=torch.long)


def decode_token_ids(token_ids: torch.Tensor, tokenizer: Optional[Any] = None) -> Optional[str | list[str]]:
    if tokenizer is None:
        return None
    ids = token_ids.detach().cpu().tolist()
    if token_ids.dim() == 2 and len(ids) == 1:
        ids = ids[0]
    elif token_ids.dim() == 2:
        return [decode_token_ids(row, tokenizer=tokenizer) or "" for row in token_ids]
    if hasattr(tokenizer, "decode"):
        return tokenizer.decode(ids)
    if hasattr(tokenizer, "idx_to_token"):
        return " ".join(tokenizer.idx_to_token.get(int(i), "<unk>") for i in ids)
    return None


def default_valid_mask(input_ids: torch.Tensor, pad_token_id: Optional[int]) -> torch.Tensor:
    if pad_token_id is None:
        return torch.ones_like(input_ids, dtype=torch.bool)
    return input_ids.ne(int(pad_token_id))


def token_hidden_state(
    model: torch.nn.Module,
    input_ids_t: torch.Tensor,
    *,
    device: torch.device,
    dtype: torch.dtype,
) -> torch.Tensor:
    embedding = getattr(model, "embedding", None)
    if embedding is None:
        batch, seq_len = input_ids_t.shape
        d_model = int(getattr(getattr(model, "config", None), "d_model", 1))
        return torch.zeros(batch, seq_len, d_model, device=device, dtype=dtype)
    hidden = embedding(input_ids_t.to(device=device, dtype=torch.long))
    if torch.is_floating_point(hidden):
        hidden = hidden.to(dtype=dtype)
    return hidden


def hidden_to_mha_kv(model: torch.nn.Module, hidden: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
    cfg = getattr(model, "config", None)
    n_heads = int(getattr(cfg, "n_heads", 1) or 1)
    head_dim = getattr(cfg, "head_dim", None)
    if head_dim is None:
        head_dim = hidden.shape[-1] // n_heads
    head_dim = int(head_dim)
    needed = n_heads * head_dim
    if hidden.shape[-1] < needed:
        hidden = torch.nn.functional.pad(hidden, (0, needed - hidden.shape[-1]))
    elif hidden.shape[-1] > needed:
        hidden = hidden[..., :needed]
    kv = hidden.reshape(hidden.shape[0], hidden.shape[1], n_heads, head_dim).transpose(1, 2)
    return kv, kv


def hidden_to_index_state(hidden: torch.Tensor, indexer_dim: int) -> torch.Tensor:
    if hidden.shape[-1] < indexer_dim:
        return torch.nn.functional.pad(hidden, (0, indexer_dim - hidden.shape[-1]))
    return hidden[..., :indexer_dim]


# ==============================================================================
# inference/mha_cache.py
# ==============================================================================

from dataclasses import dataclass
from typing import Optional

import torch



@dataclass
class MHACache:
    k: Optional[torch.Tensor] = None
    v: Optional[torch.Tensor] = None
    positions: Optional[torch.Tensor] = None
    tokens_seen: int = 0

    def append(
        self,
        k_new: torch.Tensor,
        v_new: torch.Tensor,
        position_ids: Optional[torch.Tensor] = None,
    ) -> "MHACache":
        if k_new.dim() != 4 or v_new.dim() != 4:
            raise ValueError(
                f"MHA cache expects k/v [B,H,T,Dh], got {tuple(k_new.shape)} and {tuple(v_new.shape)}"
            )
        if k_new.shape != v_new.shape:
            raise ValueError(f"k_new and v_new shapes must match, got {k_new.shape} and {v_new.shape}")

        self.k = concat_optional(self.k, k_new, dim=2)
        self.v = concat_optional(self.v, v_new, dim=2)
        if position_ids is not None:
            self.positions = concat_optional(self.positions, position_ids, dim=-1)
        self.tokens_seen += int(k_new.shape[2])
        return self

    def get_kv(self) -> tuple[Optional[torch.Tensor], Optional[torch.Tensor]]:
        return self.k, self.v

    def crop(self, max_length: Optional[int]) -> "MHACache":
        self.k = crop_last(self.k, max_length, dim=2)
        self.v = crop_last(self.v, max_length, dim=2)
        self.positions = crop_last(self.positions, max_length, dim=-1)
        return self

    def reset(self) -> None:
        self.k = None
        self.v = None
        self.positions = None
        self.tokens_seen = 0

    def num_tokens_seen(self) -> int:
        return int(self.tokens_seen)

    def memory_bytes(self) -> int:
        return tensors_memory_bytes(self.k, self.v, self.positions)

    def to(
        self,
        device: Optional[torch.device] = None,
        dtype: Optional[torch.dtype] = None,
    ) -> "MHACache":
        self.k = move_optional(self.k, device=device, dtype=dtype)
        self.v = move_optional(self.v, device=device, dtype=dtype)
        self.positions = move_optional(self.positions, device=device, dtype=None)
        return self


# ==============================================================================
# inference/hca_cache.py
# ==============================================================================

from dataclasses import dataclass
from typing import Callable, Optional

import torch



def default_hca_compressor(c: torch.Tensor, z: torch.Tensor, mask: Optional[torch.Tensor] = None) -> torch.Tensor:
    weights = torch.ones_like(c[..., :1])
    if mask is not None:
        weights = mask.to(device=c.device, dtype=c.dtype).unsqueeze(-1)
    denom = weights.sum(dim=1).clamp_min(1.0)
    c_mean = (c * weights).sum(dim=1) / denom
    z_mean = (z * weights).sum(dim=1) / denom
    return 0.5 * (c_mean + z_mean)


@dataclass
class HCALayerCache:
    compressed_kv: Optional[torch.Tensor] = None
    compressed_positions: Optional[torch.Tensor] = None
    compressed_valid_mask: Optional[torch.Tensor] = None

    local_c: Optional[torch.Tensor] = None
    local_positions: Optional[torch.Tensor] = None
    local_valid_mask: Optional[torch.Tensor] = None

    pending_c: Optional[torch.Tensor] = None
    pending_z: Optional[torch.Tensor] = None
    pending_positions: Optional[torch.Tensor] = None
    pending_mask: Optional[torch.Tensor] = None

    compression_factor: int = 1
    local_window_size: Optional[int] = None
    tokens_seen: int = 0

    def append_token_state(
        self,
        c_t: torch.Tensor,
        z_t: Optional[torch.Tensor] = None,
        position_t: Optional[torch.Tensor] = None,
        valid_mask_t: Optional[torch.Tensor] = None,
    ) -> "HCALayerCache":
        if c_t.dim() != 3:
            raise ValueError(f"c_t must have shape [B,1,D], got {tuple(c_t.shape)}")
        if z_t is None:
            z_t = c_t
        if valid_mask_t is None:
            valid_mask_t = torch.ones(c_t.shape[:2], device=c_t.device, dtype=torch.bool)

        self.pending_c = concat_optional(self.pending_c, c_t, dim=1)
        self.pending_z = concat_optional(self.pending_z, z_t, dim=1)
        if position_t is not None:
            self.pending_positions = concat_optional(self.pending_positions, position_t, dim=1)
        self.pending_mask = concat_optional(self.pending_mask, valid_mask_t.bool(), dim=1)

        self.local_c = concat_optional(self.local_c, c_t, dim=1)
        if position_t is not None:
            self.local_positions = concat_optional(self.local_positions, position_t, dim=1)
        self.local_valid_mask = concat_optional(self.local_valid_mask, valid_mask_t.bool(), dim=1)
        self.crop_local_window(self.local_window_size)

        self.tokens_seen += int(c_t.shape[1])
        return self

    def flush_ready_blocks(
        self,
        compressor: Optional[Callable[[torch.Tensor, torch.Tensor, Optional[torch.Tensor]], torch.Tensor]] = None,
    ) -> "HCALayerCache":
        if self.pending_c is None:
            return self
        compressor = compressor or default_hca_compressor
        m = max(1, int(self.compression_factor))

        while self.pending_c is not None and self.pending_c.shape[1] >= m:
            c_block = self.pending_c[:, :m]
            z_block = self.pending_z[:, :m] if self.pending_z is not None else c_block
            mask_block = self.pending_mask[:, :m] if self.pending_mask is not None else None
            compressed = compressor(c_block, z_block, mask_block).unsqueeze(1)

            self.compressed_kv = concat_optional(self.compressed_kv, compressed, dim=1)
            if self.pending_positions is not None:
                pos = self.pending_positions[:, m - 1 : m]
                self.compressed_positions = concat_optional(self.compressed_positions, pos, dim=1)
            valid = (
                mask_block.any(dim=1, keepdim=True)
                if mask_block is not None
                else torch.ones(compressed.shape[:2], device=compressed.device, dtype=torch.bool)
            )
            self.compressed_valid_mask = concat_optional(self.compressed_valid_mask, valid, dim=1)
            self._drop_pending_prefix(m)
        return self

    def _drop_pending_prefix(self, length: int) -> None:
        self.pending_c = self._drop_or_none(self.pending_c, length)
        self.pending_z = self._drop_or_none(self.pending_z, length)
        self.pending_positions = self._drop_or_none(self.pending_positions, length)
        self.pending_mask = self._drop_or_none(self.pending_mask, length)

    @staticmethod
    def _drop_or_none(tensor: Optional[torch.Tensor], length: int) -> Optional[torch.Tensor]:
        if tensor is None:
            return None
        tensor = tensor[:, length:]
        return tensor if tensor.shape[1] > 0 else None

    def get_global_kv(self) -> Optional[torch.Tensor]:
        return self.compressed_kv

    def get_local_state(self) -> tuple[Optional[torch.Tensor], Optional[torch.Tensor]]:
        return self.local_c, self.local_valid_mask

    def crop_local_window(self, window_size: Optional[int]) -> "HCALayerCache":
        self.local_c = crop_last(self.local_c, window_size, dim=1)
        self.local_positions = crop_last(self.local_positions, window_size, dim=1)
        self.local_valid_mask = crop_last(self.local_valid_mask, window_size, dim=1)
        return self

    def build_from_full_sequence(
        self,
        c: torch.Tensor,
        z: torch.Tensor,
        positions: torch.Tensor,
        valid_mask: Optional[torch.Tensor],
        compressor_fn,
    ) -> "HCALayerCache":
        if c.dim() != 3 or z.shape != c.shape:
            raise ValueError("HCA full-sequence cache expects c/z with shape [B,T,D].")
        B, T, _ = c.shape
        if positions.shape != (B, T):
            raise ValueError(f"positions must have shape {(B, T)}, got {tuple(positions.shape)}")
        if valid_mask is None:
            valid_mask = torch.ones(B, T, device=c.device, dtype=torch.bool)
        else:
            valid_mask = valid_mask.to(device=c.device, dtype=torch.bool)
            if valid_mask.shape != (B, T):
                raise ValueError(f"valid_mask must have shape {(B, T)}, got {tuple(valid_mask.shape)}")

        self.reset()
        m = max(1, int(self.compression_factor))
        n_complete = T // m
        compressed = []
        compressed_positions = []
        compressed_masks = []

        for idx in range(n_complete):
            start = idx * m
            end = start + m
            block = compressor_fn(
                c[:, start:end],
                z[:, start:end],
                valid_mask[:, start:end],
                positions[:, start:end],
            )
            compressed.append(block)
            compressed_positions.append(positions[:, end - 1])
            compressed_masks.append(valid_mask[:, start:end].any(dim=1))

        if compressed:
            self.compressed_kv = torch.stack(compressed, dim=1)
            self.compressed_positions = torch.stack(compressed_positions, dim=1)
            self.compressed_valid_mask = torch.stack(compressed_masks, dim=1)

        tail_start = n_complete * m
        if tail_start < T:
            self.pending_c = c[:, tail_start:].detach()
            self.pending_z = z[:, tail_start:].detach()
            self.pending_positions = positions[:, tail_start:].detach()
            self.pending_mask = valid_mask[:, tail_start:].detach()

        window = self.local_window_size or T
        self.local_c = c[:, max(0, T - window) :].detach()
        self.local_positions = positions[:, max(0, T - window) :].detach()
        self.local_valid_mask = valid_mask[:, max(0, T - window) :].detach()
        self.tokens_seen = int(T)
        return self

    def reset(self) -> None:
        self.compressed_kv = None
        self.compressed_positions = None
        self.compressed_valid_mask = None
        self.local_c = None
        self.local_positions = None
        self.local_valid_mask = None
        self.pending_c = None
        self.pending_z = None
        self.pending_positions = None
        self.pending_mask = None
        self.tokens_seen = 0

    def num_tokens_seen(self) -> int:
        return int(self.tokens_seen)

    def memory_bytes(self) -> int:
        return tensors_memory_bytes(
            self.compressed_kv,
            self.compressed_positions,
            self.compressed_valid_mask,
            self.local_c,
            self.local_positions,
            self.local_valid_mask,
            self.pending_c,
            self.pending_z,
            self.pending_positions,
            self.pending_mask,
        )

    def to(
        self,
        device: Optional[torch.device] = None,
        dtype: Optional[torch.dtype] = None,
    ) -> "HCALayerCache":
        for name in [
            "compressed_kv",
            "local_c",
            "pending_c",
            "pending_z",
        ]:
            setattr(self, name, move_optional(getattr(self, name), device=device, dtype=dtype))
        for name in [
            "compressed_positions",
            "compressed_valid_mask",
            "local_positions",
            "local_valid_mask",
            "pending_positions",
            "pending_mask",
        ]:
            setattr(self, name, move_optional(getattr(self, name), device=device, dtype=None))
        return self


# ==============================================================================
# inference/csa_cache.py
# ==============================================================================

from dataclasses import dataclass
from typing import Callable, Optional

import torch



def default_csa_compressor(
    current_a: torch.Tensor,
    previous_b: Optional[torch.Tensor] = None,
    mask: Optional[torch.Tensor] = None,
    **_: object,
) -> torch.Tensor:
    weights = torch.ones_like(current_a[..., :1])
    if mask is not None:
        weights = mask.to(device=current_a.device, dtype=current_a.dtype).unsqueeze(-1)
    denom = weights.sum(dim=1).clamp_min(1.0)
    current = (current_a * weights).sum(dim=1) / denom

    if previous_b is None:
        return current
    previous = previous_b.mean(dim=1)
    return 0.5 * (current + previous)


@dataclass
class CSALayerCache:
    compressed_main: Optional[torch.Tensor] = None
    compressed_index: Optional[torch.Tensor] = None
    compressed_positions: Optional[torch.Tensor] = None
    compressed_valid_mask: Optional[torch.Tensor] = None

    local_c: Optional[torch.Tensor] = None
    local_positions: Optional[torch.Tensor] = None
    local_valid_mask: Optional[torch.Tensor] = None

    pending_a_c: Optional[torch.Tensor] = None
    pending_b_c: Optional[torch.Tensor] = None
    pending_a_z: Optional[torch.Tensor] = None
    pending_b_z: Optional[torch.Tensor] = None

    pending_index_a_c: Optional[torch.Tensor] = None
    pending_index_b_c: Optional[torch.Tensor] = None
    pending_index_a_z: Optional[torch.Tensor] = None
    pending_index_b_z: Optional[torch.Tensor] = None

    pending_positions: Optional[torch.Tensor] = None
    pending_mask: Optional[torch.Tensor] = None

    previous_b_c: Optional[torch.Tensor] = None
    previous_b_z: Optional[torch.Tensor] = None
    previous_index_b_c: Optional[torch.Tensor] = None
    previous_index_b_z: Optional[torch.Tensor] = None
    previous_mask: Optional[torch.Tensor] = None

    compression_factor: int = 1
    local_window_size: Optional[int] = None
    tokens_seen: int = 0

    def append_token_state(
        self,
        a_c_t: torch.Tensor,
        b_c_t: Optional[torch.Tensor] = None,
        a_z_t: Optional[torch.Tensor] = None,
        b_z_t: Optional[torch.Tensor] = None,
        index_a_c_t: Optional[torch.Tensor] = None,
        index_b_c_t: Optional[torch.Tensor] = None,
        index_a_z_t: Optional[torch.Tensor] = None,
        index_b_z_t: Optional[torch.Tensor] = None,
        position_t: Optional[torch.Tensor] = None,
        valid_mask_t: Optional[torch.Tensor] = None,
    ) -> "CSALayerCache":
        if a_c_t.dim() != 3:
            raise ValueError(f"a_c_t must have shape [B,1,D], got {tuple(a_c_t.shape)}")

        b_c_t = b_c_t if b_c_t is not None else a_c_t
        a_z_t = a_z_t if a_z_t is not None else a_c_t
        b_z_t = b_z_t if b_z_t is not None else b_c_t
        index_a_c_t = index_a_c_t if index_a_c_t is not None else a_c_t
        index_b_c_t = index_b_c_t if index_b_c_t is not None else index_a_c_t
        index_a_z_t = index_a_z_t if index_a_z_t is not None else index_a_c_t
        index_b_z_t = index_b_z_t if index_b_z_t is not None else index_b_c_t
        if valid_mask_t is None:
            valid_mask_t = torch.ones(a_c_t.shape[:2], device=a_c_t.device, dtype=torch.bool)

        self.pending_a_c = concat_optional(self.pending_a_c, a_c_t, dim=1)
        self.pending_b_c = concat_optional(self.pending_b_c, b_c_t, dim=1)
        self.pending_a_z = concat_optional(self.pending_a_z, a_z_t, dim=1)
        self.pending_b_z = concat_optional(self.pending_b_z, b_z_t, dim=1)
        self.pending_index_a_c = concat_optional(self.pending_index_a_c, index_a_c_t, dim=1)
        self.pending_index_b_c = concat_optional(self.pending_index_b_c, index_b_c_t, dim=1)
        self.pending_index_a_z = concat_optional(self.pending_index_a_z, index_a_z_t, dim=1)
        self.pending_index_b_z = concat_optional(self.pending_index_b_z, index_b_z_t, dim=1)
        if position_t is not None:
            self.pending_positions = concat_optional(self.pending_positions, position_t, dim=1)
        self.pending_mask = concat_optional(self.pending_mask, valid_mask_t.bool(), dim=1)

        self.local_c = concat_optional(self.local_c, a_c_t.clone(), dim=1)
        if position_t is not None:
            self.local_positions = concat_optional(self.local_positions, position_t, dim=1)
        self.local_valid_mask = concat_optional(self.local_valid_mask, valid_mask_t.bool(), dim=1)
        self.crop_local_window(self.local_window_size)

        self.tokens_seen += int(a_c_t.shape[1])
        return self

    def flush_ready_blocks(
        self,
        main_compressor: Optional[
            Callable[..., torch.Tensor]
        ] = None,
        index_compressor: Optional[
            Callable[..., torch.Tensor]
        ] = None,
    ) -> "CSALayerCache":
        if self.pending_a_c is None:
            return self
        main_compressor = main_compressor or default_csa_compressor
        index_compressor = index_compressor or default_csa_compressor
        m = max(1, int(self.compression_factor))

        while self.pending_a_c is not None and self.pending_a_c.shape[1] >= m:
            mask_block = self.pending_mask[:, :m] if self.pending_mask is not None else None
            main = main_compressor(
                self.pending_a_c[:, :m],
                self.previous_b_c,
                mask_block,
                current_z=self.pending_a_z[:, :m] if self.pending_a_z is not None else None,
                previous_z=self.previous_b_z,
                previous_mask=self.previous_mask,
            ).unsqueeze(1)
            index = index_compressor(
                self.pending_index_a_c[:, :m],
                self.previous_index_b_c,
                mask_block,
                current_z=(
                    self.pending_index_a_z[:, :m] if self.pending_index_a_z is not None else None
                ),
                previous_z=self.previous_index_b_z,
                previous_mask=self.previous_mask,
            ).unsqueeze(1)

            self.compressed_main = concat_optional(self.compressed_main, main, dim=1)
            self.compressed_index = concat_optional(self.compressed_index, index, dim=1)
            if self.pending_positions is not None:
                pos = self.pending_positions[:, m - 1 : m]
                self.compressed_positions = concat_optional(self.compressed_positions, pos, dim=1)

            valid = (
                mask_block.any(dim=1, keepdim=True)
                if mask_block is not None
                else torch.ones(main.shape[:2], device=main.device, dtype=torch.bool)
            )
            self.compressed_valid_mask = concat_optional(self.compressed_valid_mask, valid, dim=1)

            self.previous_b_c = self.pending_b_c[:, :m].detach()
            self.previous_b_z = self.pending_b_z[:, :m].detach()
            self.previous_index_b_c = self.pending_index_b_c[:, :m].detach()
            self.previous_index_b_z = self.pending_index_b_z[:, :m].detach()
            self.previous_mask = mask_block.detach() if mask_block is not None else None
            self._drop_pending_prefix(m)
        return self

    def _drop_pending_prefix(self, length: int) -> None:
        for name in [
            "pending_a_c",
            "pending_b_c",
            "pending_a_z",
            "pending_b_z",
            "pending_index_a_c",
            "pending_index_b_c",
            "pending_index_a_z",
            "pending_index_b_z",
            "pending_positions",
            "pending_mask",
        ]:
            tensor = getattr(self, name)
            if tensor is None:
                continue
            tensor = tensor[:, length:]
            setattr(self, name, tensor if tensor.shape[1] > 0 else None)

    def crop_local_window(self, window_size: Optional[int]) -> "CSALayerCache":
        self.local_c = crop_last(self.local_c, window_size, dim=1)
        self.local_positions = crop_last(self.local_positions, window_size, dim=1)
        self.local_valid_mask = crop_last(self.local_valid_mask, window_size, dim=1)
        return self

    def get_global_state(self) -> tuple[Optional[torch.Tensor], Optional[torch.Tensor]]:
        return self.compressed_main, self.compressed_index

    def get_local_state(self) -> tuple[Optional[torch.Tensor], Optional[torch.Tensor]]:
        return self.local_c, self.local_valid_mask

    def reset(self) -> None:
        for name in [
            "compressed_main",
            "compressed_index",
            "compressed_positions",
            "compressed_valid_mask",
            "local_c",
            "local_positions",
            "local_valid_mask",
            "pending_a_c",
            "pending_b_c",
            "pending_a_z",
            "pending_b_z",
            "pending_index_a_c",
            "pending_index_b_c",
            "pending_index_a_z",
            "pending_index_b_z",
            "pending_positions",
            "pending_mask",
            "previous_b_c",
            "previous_b_z",
            "previous_index_b_c",
            "previous_index_b_z",
            "previous_mask",
        ]:
            setattr(self, name, None)
        self.tokens_seen = 0

    def build_from_full_sequence(
        self,
        a_c: torch.Tensor,
        b_c: torch.Tensor,
        a_z: torch.Tensor,
        b_z: torch.Tensor,
        index_a_c: torch.Tensor,
        index_b_c: torch.Tensor,
        index_a_z: torch.Tensor,
        index_b_z: torch.Tensor,
        positions: torch.Tensor,
        valid_mask: Optional[torch.Tensor],
        main_compressor_fn,
        index_compressor_fn,
        local_c: Optional[torch.Tensor] = None,
    ) -> "CSALayerCache":
        if a_c.dim() != 3:
            raise ValueError("CSA full-sequence cache expects states with shape [B,T,D].")
        for tensor in [b_c, a_z, b_z]:
            if tensor.shape != a_c.shape:
                raise ValueError("CSA main a/b c/z states must share shape.")
        for tensor in [index_b_c, index_a_z, index_b_z]:
            if tensor.shape != index_a_c.shape:
                raise ValueError("CSA index a/b c/z states must share shape.")

        B, T, _ = a_c.shape
        if positions.shape != (B, T):
            raise ValueError(f"positions must have shape {(B, T)}, got {tuple(positions.shape)}")
        if valid_mask is None:
            valid_mask = torch.ones(B, T, device=a_c.device, dtype=torch.bool)
        else:
            valid_mask = valid_mask.to(device=a_c.device, dtype=torch.bool)
            if valid_mask.shape != (B, T):
                raise ValueError(f"valid_mask must have shape {(B, T)}, got {tuple(valid_mask.shape)}")

        self.reset()
        m = max(1, int(self.compression_factor))
        n_complete = T // m
        comp_main = []
        comp_index = []
        comp_positions = []
        comp_masks = []
        prev_b = None
        prev_bz = None
        prev_ib = None
        prev_ibz = None
        prev_mask = None

        for idx in range(n_complete):
            start = idx * m
            end = start + m
            mask_block = valid_mask[:, start:end]
            main = main_compressor_fn(
                a_c[:, start:end],
                prev_b,
                mask_block,
                current_z=a_z[:, start:end],
                previous_z=prev_bz,
                previous_mask=prev_mask,
            )
            index = index_compressor_fn(
                index_a_c[:, start:end],
                prev_ib,
                mask_block,
                current_z=index_a_z[:, start:end],
                previous_z=prev_ibz,
                previous_mask=prev_mask,
            )
            comp_main.append(main)
            comp_index.append(index)
            comp_positions.append(positions[:, end - 1])
            comp_masks.append(mask_block.any(dim=1))

            prev_b = b_c[:, start:end].detach()
            prev_bz = b_z[:, start:end].detach()
            prev_ib = index_b_c[:, start:end].detach()
            prev_ibz = index_b_z[:, start:end].detach()
            prev_mask = mask_block.detach()

        if comp_main:
            self.compressed_main = torch.stack(comp_main, dim=1)
            self.compressed_index = torch.stack(comp_index, dim=1)
            self.compressed_positions = torch.stack(comp_positions, dim=1)
            self.compressed_valid_mask = torch.stack(comp_masks, dim=1)

        self.previous_b_c = prev_b
        self.previous_b_z = prev_bz
        self.previous_index_b_c = prev_ib
        self.previous_index_b_z = prev_ibz
        self.previous_mask = prev_mask

        tail_start = n_complete * m
        if tail_start < T:
            self.pending_a_c = a_c[:, tail_start:].detach()
            self.pending_b_c = b_c[:, tail_start:].detach()
            self.pending_a_z = a_z[:, tail_start:].detach()
            self.pending_b_z = b_z[:, tail_start:].detach()
            self.pending_index_a_c = index_a_c[:, tail_start:].detach()
            self.pending_index_b_c = index_b_c[:, tail_start:].detach()
            self.pending_index_a_z = index_a_z[:, tail_start:].detach()
            self.pending_index_b_z = index_b_z[:, tail_start:].detach()
            self.pending_positions = positions[:, tail_start:].detach()
            self.pending_mask = valid_mask[:, tail_start:].detach()

        local_source = local_c if local_c is not None else a_c
        window = self.local_window_size or T
        self.local_c = local_source[:, max(0, T - window) :].detach()
        self.local_positions = positions[:, max(0, T - window) :].detach()
        self.local_valid_mask = valid_mask[:, max(0, T - window) :].detach()
        self.tokens_seen = int(T)
        return self

    def num_tokens_seen(self) -> int:
        return int(self.tokens_seen)

    def memory_bytes(self) -> int:
        return tensors_memory_bytes(
            self.compressed_main,
            self.compressed_index,
            self.compressed_positions,
            self.compressed_valid_mask,
            self.local_c,
            self.local_positions,
            self.local_valid_mask,
            self.pending_a_c,
            self.pending_b_c,
            self.pending_a_z,
            self.pending_b_z,
            self.pending_index_a_c,
            self.pending_index_b_c,
            self.pending_index_a_z,
            self.pending_index_b_z,
            self.pending_positions,
            self.pending_mask,
            self.previous_b_c,
            self.previous_b_z,
            self.previous_index_b_c,
            self.previous_index_b_z,
            self.previous_mask,
        )

    def to(
        self,
        device: Optional[torch.device] = None,
        dtype: Optional[torch.dtype] = None,
    ) -> "CSALayerCache":
        floating = [
            "compressed_main",
            "compressed_index",
            "local_c",
            "pending_a_c",
            "pending_b_c",
            "pending_a_z",
            "pending_b_z",
            "pending_index_a_c",
            "pending_index_b_c",
            "pending_index_a_z",
            "pending_index_b_z",
            "previous_b_c",
            "previous_b_z",
            "previous_index_b_c",
            "previous_index_b_z",
        ]
        for name in floating:
            setattr(self, name, move_optional(getattr(self, name), device=device, dtype=dtype))
        for name in [
            "compressed_positions",
            "compressed_valid_mask",
            "local_positions",
            "local_valid_mask",
            "pending_positions",
            "pending_mask",
            "previous_mask",
        ]:
            setattr(self, name, move_optional(getattr(self, name), device=device, dtype=None))
        return self


# ==============================================================================
# inference/hybrid_cache.py
# ==============================================================================

from dataclasses import dataclass, field
from typing import Any, Optional

import torch



@dataclass
class DeepSeekV4InferenceCache:
    layer_caches: list[Any]
    batch_size: int
    device: torch.device
    dtype: torch.dtype
    tokens_seen: int = 0
    sequence_ids: Optional[torch.Tensor] = None
    attention_mask: Optional[torch.Tensor] = None
    metadata: dict[str, Any] = field(default_factory=dict)

    def reset(self) -> None:
        for cache in self.layer_caches:
            cache.reset()
        self.tokens_seen = 0
        self.sequence_ids = None
        self.attention_mask = None
        self.metadata.clear()

    def to(
        self,
        device: Optional[torch.device] = None,
        dtype: Optional[torch.dtype] = None,
    ) -> "DeepSeekV4InferenceCache":
        if device is not None:
            self.device = device
        if dtype is not None:
            self.dtype = dtype
        for cache in self.layer_caches:
            cache.to(device=device, dtype=dtype)
        if self.sequence_ids is not None and device is not None:
            self.sequence_ids = self.sequence_ids.to(device=device)
        if self.attention_mask is not None and device is not None:
            self.attention_mask = self.attention_mask.to(device=device)
        return self

    def append_input_ids(
        self,
        input_ids_t: torch.Tensor,
        attention_mask_t: Optional[torch.Tensor] = None,
    ) -> None:
        input_ids_t = input_ids_t.to(device=self.device, dtype=torch.long)
        self.sequence_ids = (
            input_ids_t if self.sequence_ids is None else torch.cat([self.sequence_ids, input_ids_t], dim=1)
        )
        if attention_mask_t is not None:
            attention_mask_t = attention_mask_t.to(device=self.device)
            self.attention_mask = (
                attention_mask_t
                if self.attention_mask is None
                else torch.cat([self.attention_mask, attention_mask_t], dim=1)
            )
        self.tokens_seen += int(input_ids_t.shape[1])

    def crop_sequence(self, max_length: Optional[int]) -> None:
        if max_length is None:
            return
        if self.sequence_ids is not None and self.sequence_ids.shape[1] > max_length:
            self.sequence_ids = self.sequence_ids[:, -max_length:]
        if self.attention_mask is not None and self.attention_mask.shape[1] > max_length:
            self.attention_mask = self.attention_mask[:, -max_length:]
        for cache in self.layer_caches:
            if hasattr(cache, "crop"):
                cache.crop(max_length)

    def memory_bytes(self) -> int:
        total = sum(cache.memory_bytes() for cache in self.layer_caches)
        if self.sequence_ids is not None:
            total += int(self.sequence_ids.numel() * self.sequence_ids.element_size())
        if self.attention_mask is not None:
            total += int(self.attention_mask.numel() * self.attention_mask.element_size())
        return total

    def cache_summary(self) -> dict[str, Any]:
        by_type: dict[str, int] = {}
        compressed_hca = 0
        compressed_csa = 0
        pending_hca = 0
        pending_csa = 0
        local_windows: list[int] = []

        for cache in self.layer_caches:
            name = type(cache).__name__
            by_type[name] = by_type.get(name, 0) + 1
            if isinstance(cache, HCALayerCache):
                compressed_hca += 0 if cache.compressed_kv is None else int(cache.compressed_kv.shape[1])
                pending_hca += 0 if cache.pending_c is None else int(cache.pending_c.shape[1])
                if cache.local_c is not None:
                    local_windows.append(int(cache.local_c.shape[1]))
            elif isinstance(cache, CSALayerCache):
                compressed_csa += 0 if cache.compressed_main is None else int(cache.compressed_main.shape[1])
                pending_csa += 0 if cache.pending_a_c is None else int(cache.pending_a_c.shape[1])
                if cache.local_c is not None:
                    local_windows.append(int(cache.local_c.shape[1]))

        return {
            "batch_size": self.batch_size,
            "tokens_seen": self.tokens_seen,
            "sequence_length": 0 if self.sequence_ids is None else int(self.sequence_ids.shape[1]),
            "device": str(self.device),
            "dtype": str(self.dtype).replace("torch.", ""),
            "cache_mode": self.metadata.get("cache_mode", "unknown"),
            "active_decode": bool(self.metadata.get("active_decode", False)),
            "logits_from_cache": bool(self.metadata.get("logits_from_cache", False)),
            "cache_population": self.metadata.get("cache_population", "unknown"),
            "deepseek_active_decode": bool(
                self.metadata.get("cache_mode") == "deepseek_decode"
                and self.metadata.get("logits_from_cache", False)
            ),
            "num_layers": len(self.layer_caches),
            "layers_by_cache_type": by_type,
            "cache_memory_bytes": self.memory_bytes(),
            "cache_memory_mb": self.memory_bytes() / (1024 * 1024),
            "num_compressed_entries_hca": compressed_hca,
            "num_compressed_entries_csa": compressed_csa,
            "num_pending_tokens_hca": pending_hca,
            "num_pending_tokens_csa": pending_csa,
            "num_hca_compressed_entries": compressed_hca,
            "num_csa_compressed_main_entries": compressed_csa,
            "num_csa_compressed_index_entries": compressed_csa,
            "num_hca_pending_tokens": pending_hca,
            "num_csa_pending_tokens": pending_csa,
            "local_window_size": max(local_windows) if local_windows else 0,
        }


def _layer_cache_type(block: torch.nn.Module) -> str:
    return str(getattr(block, "attention_type", "mha"))


def build_inference_cache(
    model: torch.nn.Module,
    batch_size: int,
    device: torch.device,
    dtype: str | torch.dtype,
    local_window_size: Optional[int] = None,
) -> DeepSeekV4InferenceCache:
    cfg = getattr(model, "config", None)
    cache_dtype = resolve_cache_dtype(dtype)
    layer_caches: list[Any] = []

    for block in getattr(model, "blocks", []):
        attention_type = _layer_cache_type(block)
        if attention_type == "mha":
            layer_caches.append(MHACache())
        elif attention_type == "hca":
            layer_caches.append(
                HCALayerCache(
                    compression_factor=int(getattr(cfg, "hca_compression_factor", 1) or 1),
                    local_window_size=local_window_size or getattr(cfg, "window_size", None),
                )
            )
        elif attention_type == "csa":
            layer_caches.append(
                CSALayerCache(
                    compression_factor=int(getattr(cfg, "compression_factor", 1) or 1),
                    local_window_size=local_window_size or getattr(cfg, "window_size", None),
                )
            )
        else:
            raise ValueError(f"Unsupported attention type for inference cache: {attention_type!r}")

    return DeepSeekV4InferenceCache(
        layer_caches=layer_caches,
        batch_size=batch_size,
        device=device,
        dtype=cache_dtype,
        metadata={
            "cache_mode": "unconfigured",
            "active_decode": False,
            "logits_from_cache": False,
            "cache_population": "unconfigured",
        },
    )


# ==============================================================================
# inference/deepseek_cache_builder.py
# ==============================================================================

from typing import Optional

import torch



class DeepSeekActiveCacheBuilder:
    def __init__(self, cache, inference_config):
        self.cache = cache
        self.cfg = inference_config

    def capture_layer_input(
        self,
        layer_idx: int,
        attention_type: str,
        attention_module: torch.nn.Module,
        x_norm: torch.Tensor,
        position_ids: torch.Tensor,
        attention_mask: Optional[torch.Tensor],
    ) -> None:
        layer_cache = self.cache.layer_caches[layer_idx]

        if attention_type == "mha":
            if not isinstance(layer_cache, MHACache):
                raise TypeError("MHA attention requires MHACache.")
            if not all(hasattr(attention_module, name) for name in ("k_proj", "v_proj", "_shape_projection")):
                raise NotImplementedError("MHA parallel prefill requires k/v projection helpers.")
            layer_cache.reset()
            k = attention_module._shape_projection(attention_module.k_proj(x_norm))
            v = attention_module._shape_projection(attention_module.v_proj(x_norm))
            if getattr(attention_module, "rope", None) is not None:
                k = attention_module.rope(k, position_ids=position_ids, start_pos=0)
            layer_cache.append(k.transpose(1, 2), v.transpose(1, 2), position_ids)
            return

        if attention_type == "hca":
            if not isinstance(layer_cache, HCALayerCache):
                raise TypeError("HCA attention requires HCALayerCache.")
            if not hasattr(attention_module, "project_cache_states_full"):
                raise NotImplementedError("HCA parallel prefill requires project_cache_states_full.")
            states = attention_module.project_cache_states_full(x_norm)
            layer_cache.build_from_full_sequence(
                c=states["c"],
                z=states["z"],
                positions=position_ids,
                valid_mask=attention_mask,
                compressor_fn=attention_module.compress_hca_block_for_cache,
            )
            return

        if attention_type == "csa":
            if not isinstance(layer_cache, CSALayerCache):
                raise TypeError("CSA attention requires CSALayerCache.")
            if not hasattr(attention_module, "project_cache_states_full"):
                raise NotImplementedError("CSA parallel prefill requires project_cache_states_full.")
            states = attention_module.project_cache_states_full(x_norm)
            layer_cache.build_from_full_sequence(
                a_c=states["a_c"],
                b_c=states["b_c"],
                a_z=states["a_z"],
                b_z=states["b_z"],
                index_a_c=states["index_a_c"],
                index_b_c=states["index_b_c"],
                index_a_z=states["index_a_z"],
                index_b_z=states["index_b_z"],
                positions=position_ids,
                valid_mask=attention_mask,
                main_compressor_fn=attention_module.compress_csa_main_block_for_cache,
                index_compressor_fn=attention_module.compress_csa_index_block_for_cache,
                local_c=states.get("local_c"),
            )
            return

        raise NotImplementedError(f"Unsupported attention type for DeepSeek cache builder: {attention_type!r}")


# ==============================================================================
# inference/sampling.py
# ==============================================================================

import torch



def apply_repetition_penalty(
    logits: torch.Tensor,
    generated_ids: torch.Tensor,
    penalty: float | None,
) -> torch.Tensor:
    if penalty is None or penalty == 1.0:
        return logits
    if penalty <= 0:
        raise ValueError(f"penalty must be > 0, got {penalty}")

    logits = logits.clone()
    for batch_idx in range(logits.shape[0]):
        seen = torch.unique(generated_ids[batch_idx].to(device=logits.device, dtype=torch.long))
        token_logits = logits[batch_idx, seen]
        logits[batch_idx, seen] = torch.where(token_logits < 0, token_logits * penalty, token_logits / penalty)
    return logits


def top_k_filtering(logits: torch.Tensor, top_k: int | None) -> torch.Tensor:
    if top_k is None:
        return logits
    top_k = min(int(top_k), logits.shape[-1])
    values, _ = torch.topk(logits, k=top_k, dim=-1)
    cutoff = values[..., -1, None]
    return logits.masked_fill(logits < cutoff, float("-inf"))


def top_p_filtering(logits: torch.Tensor, top_p: float | None) -> torch.Tensor:
    if top_p is None or top_p >= 1.0:
        return logits
    sorted_logits, sorted_indices = torch.sort(logits, descending=True, dim=-1)
    probs = torch.softmax(sorted_logits, dim=-1)
    cumulative = torch.cumsum(probs, dim=-1)

    remove = cumulative > top_p
    remove[..., 1:] = remove[..., :-1].clone()
    remove[..., 0] = False

    filtered_sorted = sorted_logits.masked_fill(remove, float("-inf"))
    filtered = torch.empty_like(logits)
    filtered.scatter_(dim=-1, index=sorted_indices, src=filtered_sorted)
    return filtered


def _safe_argmax(logits: torch.Tensor) -> torch.Tensor:
    clean_logits = torch.nan_to_num(logits, nan=float("-inf"), posinf=1e30, neginf=-1e30)
    return torch.argmax(clean_logits, dim=-1, keepdim=True)


def sample_next_token(
    logits: torch.Tensor,
    config: InferenceConfig,
    generated_ids: torch.Tensor | None = None,
) -> torch.Tensor:
    config.validate()
    if logits.dim() != 2:
        raise ValueError(f"sample_next_token expects logits [B,V], got {tuple(logits.shape)}")

    if not torch.isfinite(logits).all():
        return _safe_argmax(logits)

    if generated_ids is not None:
        logits = apply_repetition_penalty(logits, generated_ids, config.repetition_penalty)

    if not config.do_sample:
        return _safe_argmax(logits)

    logits = logits / config.temperature
    logits = top_k_filtering(logits, config.top_k)
    logits = top_p_filtering(logits, config.top_p)

    probs = torch.softmax(logits, dim=-1)
    valid = torch.isfinite(probs).all(dim=-1) & (probs.sum(dim=-1) > 0)
    if not bool(valid.all().item()):
        return _safe_argmax(logits)

    return torch.multinomial(probs, num_samples=1)


# ==============================================================================
# inference/mtp_decode.py
# ==============================================================================

from typing import Any, Optional

import torch



@torch.no_grad()
def mtp_draft_from_hidden(
    model: torch.nn.Module,
    hidden_states: Optional[torch.Tensor],
    inference_config: Optional[InferenceConfig] = None,
) -> dict[str, Any]:
    cfg = inference_config or InferenceConfig()
    cfg.validate()

    mtp_head = getattr(model, "mtp_head", None)
    if hidden_states is None or mtp_head is None or not getattr(model, "use_mtp", False):
        return {
            "enabled": False,
            "mtp_logits": None,
            "draft_token_ids": None,
            "draft_confidence": None,
            "is_speculative_decode": False,
        }

    outputs = mtp_head(hidden_states[:, -1:, :], mtp_labels=None, return_aux=False)
    logits = outputs["mtp_logits"]
    max_tokens = cfg.max_mtp_draft_tokens or logits.shape[1]
    max_tokens = min(max_tokens, logits.shape[1])
    draft_logits = logits[:, :max_tokens, -1, :]
    draft_probs = torch.softmax(draft_logits.float(), dim=-1)
    draft_confidence, draft_ids = torch.max(draft_probs, dim=-1)

    return {
        "enabled": bool(cfg.use_mtp_draft),
        "accept_mode": cfg.mtp_accept_mode,
        "mtp_logits": logits,
        "draft_token_ids": draft_ids,
        "draft_confidence": draft_confidence,
        "is_speculative_decode": False,
    }


# ==============================================================================
# inference/decode.py
# ==============================================================================

from typing import Any, Optional

import torch



def configure_cache_metadata(cache: DeepSeekV4InferenceCache, cfg: InferenceConfig) -> None:
    cache.metadata["cache_mode"] = cfg.cache_mode
    cache.metadata["active_decode"] = cfg.cache_mode in {"mha_decode", "deepseek_decode"}
    cache.metadata["logits_from_cache"] = cfg.cache_mode in {"mha_decode", "deepseek_decode"}
    if cfg.cache_mode == "mha_decode":
        cache.metadata["cache_population"] = "active_mha_kv"
    elif cfg.cache_mode == "deepseek_decode":
        cache.metadata["cache_population"] = cfg.deepseek_cache_population
    else:
        cache.metadata["cache_population"] = "embedding_proxy"


def _layer_hidden_for_cache(
    model: torch.nn.Module,
    input_ids_t: torch.Tensor,
    cache: DeepSeekV4InferenceCache,
) -> torch.Tensor:
    return token_hidden_state(
        model,
        input_ids_t,
        device=cache.device,
        dtype=cache.dtype,
    )


def update_cache_with_token(
    model: torch.nn.Module,
    input_ids_t: torch.Tensor,
    cache: DeepSeekV4InferenceCache,
    position_ids_t: Optional[torch.Tensor] = None,
    attention_mask_t: Optional[torch.Tensor] = None,
    inference_config: Optional[InferenceConfig] = None,
) -> DeepSeekV4InferenceCache:
    cfg = inference_config or InferenceConfig()
    cfg.validate()
    configure_cache_metadata(cache, cfg)

    input_ids_t = input_ids_t.to(device=cache.device, dtype=torch.long)
    if input_ids_t.dim() != 2 or input_ids_t.shape[1] != 1:
        raise ValueError(f"input_ids_t must have shape [B,1], got {tuple(input_ids_t.shape)}")

    position_ids_t = normalize_position_ids(
        position_ids_t,
        batch_size=input_ids_t.shape[0],
        seq_len=1,
        start_pos=cache.tokens_seen,
        device=cache.device,
    )
    pad_token_id = cfg.pad_token_id
    if pad_token_id is None:
        pad_token_id = getattr(model, "pad_token_id", None)

    valid_mask_t = (
        attention_mask_t.to(device=cache.device).bool()
        if attention_mask_t is not None
        else default_valid_mask(input_ids_t, pad_token_id)
    )
    hidden = _layer_hidden_for_cache(model, input_ids_t, cache)
    index_dim = int(getattr(getattr(model, "config", None), "indexer_dim", hidden.shape[-1]))

    for layer_cache in cache.layer_caches:
        if isinstance(layer_cache, MHACache):
            k_t, v_t = hidden_to_mha_kv(model, hidden)
            layer_cache.append(k_t, v_t, position_ids_t)
            layer_cache.crop(cfg.max_cache_length)
        elif isinstance(layer_cache, HCALayerCache):
            layer_cache.append_token_state(hidden, hidden, position_ids_t, valid_mask_t)
            if cfg.compress_on_block_ready:
                layer_cache.flush_ready_blocks()
        elif isinstance(layer_cache, CSALayerCache):
            index_state = hidden_to_index_state(hidden, index_dim)
            layer_cache.append_token_state(
                a_c_t=hidden,
                b_c_t=hidden,
                a_z_t=hidden,
                b_z_t=hidden,
                index_a_c_t=index_state,
                index_b_c_t=index_state,
                index_a_z_t=index_state,
                index_b_z_t=index_state,
                position_t=position_ids_t,
                valid_mask_t=valid_mask_t,
            )
            if cfg.compress_on_block_ready:
                layer_cache.flush_ready_blocks()

    cache.append_input_ids(input_ids_t, valid_mask_t.long())
    cache.crop_sequence(cfg.max_cache_length)
    return cache


def _full_forward_decode(
    model: torch.nn.Module,
    cache: DeepSeekV4InferenceCache,
    *,
    return_aux: bool,
) -> dict[str, Any]:
    if cache.sequence_ids is None:
        raise ValueError("cache.sequence_ids is empty; call prefill or update_cache_with_token first.")

    max_context = context_window_for_model(model, None)
    input_ids = cache.sequence_ids[:, -max_context:]
    attention_mask = cache.attention_mask[:, -input_ids.shape[1] :] if cache.attention_mask is not None else None
    outputs = model(
        input_ids=input_ids,
        attention_mask=attention_mask,
        return_aux=return_aux,
    )
    return {
        "logits": outputs["logits"][:, -1:, :],
        "hidden_states": outputs.get("hidden_states", None),
        "aux": outputs.get("aux", {}),
    }


@torch.no_grad()
def decode_step(
    model: torch.nn.Module,
    input_ids_t: torch.Tensor,
    cache: DeepSeekV4InferenceCache,
    position_ids_t: Optional[torch.Tensor] = None,
    inference_config: Optional[InferenceConfig] = None,
    return_aux: bool = False,
) -> dict[str, Any]:
    cfg = inference_config or InferenceConfig()
    cfg.validate()

    if cache is None:
        raise ValueError("decode_step requires a DeepSeekV4InferenceCache instance.")

    if cfg.cache_mode in {"mha_decode", "deepseek_decode"}:
        model_cfg = getattr(model, "config", None)
        if cfg.cache_mode == "mha_decode" and getattr(model_cfg, "attention_type", None) != "mha":
            raise NotImplementedError("cache_mode='mha_decode' only supports attention_type='mha'.")
        if not hasattr(model, "forward_decode"):
            raise NotImplementedError("Model does not expose forward_decode for active cached decoding.")

        configure_cache_metadata(cache, cfg)
        decoded = model.forward_decode(
            input_ids_t=input_ids_t,
            cache=cache,
            position_ids_t=position_ids_t,
            attention_mask_t=None,
            return_aux=return_aux,
        )
    else:
        update_cache_with_token(
            model,
            input_ids_t=input_ids_t,
            cache=cache,
            position_ids_t=position_ids_t,
            inference_config=cfg,
        )
        decoded = _full_forward_decode(model, cache, return_aux=return_aux)
        decoded["cache"] = cache
        decoded["aux"] = decoded.get("aux", {})

    if return_aux:
        decoded["aux"]["cache_summary"] = cache.cache_summary()
    return decoded


def next_position_ids(cache: DeepSeekV4InferenceCache) -> torch.Tensor:
    return torch.full(
        (cache.batch_size, 1),
        fill_value=int(cache.tokens_seen),
        device=cache.device,
        dtype=torch.long,
    )


def prepare_input_ids(input_ids: torch.Tensor, model: torch.nn.Module, cfg: InferenceConfig) -> torch.Tensor:
    device = resolve_device(model, cfg.device)
    return input_ids.to(device=device, dtype=torch.long)


# ==============================================================================
# inference/prefill.py
# ==============================================================================

from typing import Any, Optional

import torch



@torch.no_grad()
def prefill(
    model: torch.nn.Module,
    input_ids: torch.Tensor,
    attention_mask: Optional[torch.Tensor] = None,
    position_ids: Optional[torch.Tensor] = None,
    inference_config: Optional[InferenceConfig] = None,
    return_aux: bool = False,
) -> dict[str, Any]:
    cfg = inference_config or InferenceConfig()
    cfg.validate()

    device = resolve_device(model, cfg.device)
    cache_dtype = resolve_cache_dtype(cfg.cache_dtype)
    input_ids = input_ids.to(device=device, dtype=torch.long)
    if input_ids.dim() != 2:
        raise ValueError(f"input_ids must have shape [B,T], got {tuple(input_ids.shape)}")
    if input_ids.shape[1] == 0:
        raise ValueError("prefill requires at least one prompt token.")

    if attention_mask is not None:
        attention_mask = attention_mask.to(device=device)

    batch_size, seq_len = input_ids.shape
    position_ids = normalize_position_ids(
        position_ids,
        batch_size=batch_size,
        seq_len=seq_len,
        device=device,
    )
    cache = build_inference_cache(
        model,
        batch_size=batch_size,
        device=device,
        dtype=cache_dtype,
        local_window_size=cfg.local_window_size,
    )
    configure_cache_metadata(cache, cfg)

    if cfg.cache_mode == "deepseek_decode" and cfg.deepseek_prefill_mode == "parallel":
        if not hasattr(model, "prefill_decode_cache"):
            raise NotImplementedError(
                "cache_mode='deepseek_decode' with deepseek_prefill_mode='parallel' "
                "requires model.prefill_decode_cache(...)."
            )
        out = model.prefill_decode_cache(
            input_ids=input_ids,
            cache=cache,
            attention_mask=attention_mask,
            position_ids=position_ids,
            inference_config=cfg,
            return_aux=return_aux,
        )
        if return_aux:
            aux = out.get("aux", {})
            aux["cache_summary"] = out["cache"].cache_summary()
            out["aux"] = aux
        return out

    if cfg.cache_mode in {"mha_decode", "deepseek_decode"}:
        if getattr(getattr(model, "config", None), "attention_type", None) != "mha":
            if cfg.cache_mode == "mha_decode":
                raise NotImplementedError("cache_mode='mha_decode' only supports attention_type='mha'.")
        logits_steps = []
        hidden_states = None
        aux = {}
        for idx in range(seq_len):
            mask_t = attention_mask[:, idx : idx + 1] if attention_mask is not None else None
            out = model.forward_decode(
                input_ids_t=input_ids[:, idx : idx + 1],
                cache=cache,
                position_ids_t=position_ids[:, idx : idx + 1],
                attention_mask_t=mask_t,
                return_aux=return_aux,
            )
            cache = out["cache"]
            logits_steps.append(out["logits"])
            hidden_states = out.get("hidden_states")
            aux = out.get("aux", {})

        full_logits = torch.cat(logits_steps, dim=1)
        if return_aux:
            aux["cache_summary"] = cache.cache_summary()
        return {
            "logits": full_logits[:, -1:, :],
            "full_logits": full_logits,
            "hidden_states": hidden_states,
            "cache": cache,
            "aux": aux if return_aux else {},
        }

    for idx in range(seq_len):
        mask_t = attention_mask[:, idx : idx + 1] if attention_mask is not None else None
        update_cache_with_token(
            model,
            input_ids_t=input_ids[:, idx : idx + 1],
            cache=cache,
            position_ids_t=position_ids[:, idx : idx + 1],
            attention_mask_t=mask_t,
            inference_config=cfg,
        )

    outputs = model(
        input_ids=input_ids,
        attention_mask=attention_mask,
        position_ids=position_ids,
        return_aux=return_aux,
    )
    aux = outputs.get("aux", {}) if return_aux else {}
    if return_aux:
        aux["cache_summary"] = cache.cache_summary()

    return {
        "logits": outputs["logits"][:, -1:, :],
        "full_logits": outputs["logits"],
        "hidden_states": outputs.get("hidden_states", None),
        "cache": cache,
        "aux": aux,
    }


def empty_cache_like_prefill(
    model: torch.nn.Module,
    input_ids: torch.Tensor,
    inference_config: Optional[InferenceConfig] = None,
) -> DeepSeekV4InferenceCache:
    cfg = inference_config or InferenceConfig()
    device = resolve_device(model, cfg.device)
    return build_inference_cache(
        model,
        batch_size=int(input_ids.shape[0]),
        device=device,
        dtype=resolve_cache_dtype(cfg.cache_dtype),
        local_window_size=cfg.local_window_size,
    )


# ==============================================================================
# inference/metrics.py
# ==============================================================================

import time
from typing import Any, Optional

import torch



def cache_memory_bytes(cache: Any) -> int:
    if cache is None:
        return 0
    if hasattr(cache, "memory_bytes"):
        return int(cache.memory_bytes())
    return 0


def cache_summary(cache: Any) -> dict[str, Any]:
    if cache is None:
        return {}
    if hasattr(cache, "cache_summary"):
        return cache.cache_summary()
    return {"cache_memory_bytes": cache_memory_bytes(cache)}


def generation_speed_metrics(start_time: float, end_time: float, num_tokens: int) -> dict[str, float]:
    elapsed = max(float(end_time) - float(start_time), 0.0)
    return {
        "elapsed_seconds": elapsed,
        "num_generated_tokens": float(num_tokens),
        "tokens_per_second": float(num_tokens) / elapsed if elapsed > 0 else 0.0,
    }


@torch.no_grad()
def compare_full_vs_cached_logits(
    model: torch.nn.Module,
    input_ids: torch.Tensor,
    inference_config: Optional[InferenceConfig] = None,
    atol: float = 1e-4,
    rtol: float = 1e-4,
) -> dict[str, Any]:
    cfg = inference_config or InferenceConfig(do_sample=False)
    cfg.validate()
    was_training = model.training
    model.eval()

    full = model(input_ids=input_ids)["logits"]
    cached_positions = []
    max_diff = 0.0
    cache = None
    try:
        for idx in range(input_ids.shape[1]):
            out = prefill(
                model,
                input_ids=input_ids[:, : idx + 1],
                inference_config=cfg,
                return_aux=False,
            )
            cache = out["cache"]
            cached = out["logits"][:, -1, :]
            target = full[:, idx, :]
            diff = torch.max(torch.abs(cached - target)).item()
            max_diff = max(max_diff, float(diff))
            cached_positions.append(bool(torch.allclose(cached, target, atol=atol, rtol=rtol)))
    finally:
        if was_training:
            model.train()

    return {
        "allclose": all(cached_positions),
        "per_position_allclose": cached_positions,
        "max_abs_diff": max_diff,
        "atol": atol,
        "rtol": rtol,
        "cache_summary": cache_summary(cache),
    }


def now() -> float:
    return time.perf_counter()


# ==============================================================================
# inference/generate.py
# ==============================================================================

from typing import Any, Optional

import torch



@torch.no_grad()
def generate(
    model: torch.nn.Module,
    input_ids: torch.Tensor,
    inference_config: InferenceConfig,
    attention_mask: Optional[torch.Tensor] = None,
    return_dict: bool = True,
) -> dict[str, Any] | torch.Tensor:
    inference_config.validate()
    was_training = model.training
    model.eval()

    device = resolve_device(model, inference_config.device)
    input_ids = input_ids.to(device=device, dtype=torch.long)
    if attention_mask is not None:
        attention_mask = attention_mask.to(device=device)

    start = now()
    prompt_len = int(input_ids.shape[1])
    prefill_start = now()
    prefill_out = prefill(
        model,
        input_ids=input_ids,
        attention_mask=attention_mask,
        inference_config=inference_config,
        return_aux=inference_config.use_mtp_draft or inference_config.return_cache_stats,
    )
    prefill_end = now()

    cache = prefill_out["cache"]
    sequences = input_ids
    logits = prefill_out["logits"][:, -1, :]
    scores: list[torch.Tensor] = []
    mtp_drafts: list[dict[str, Any]] = []
    finished = torch.zeros(input_ids.shape[0], device=device, dtype=torch.bool)

    hidden_states = prefill_out.get("hidden_states")
    if inference_config.use_mtp_draft:
        mtp_drafts.append(mtp_draft_from_hidden(model, hidden_states, inference_config))

    decode_time = 0.0
    for _ in range(inference_config.max_new_tokens):
        if inference_config.return_cache_stats:
            scores.append(logits.detach().cpu())

        next_token = sample_next_token(logits, inference_config, sequences)
        if inference_config.eos_token_id is not None:
            eos = int(inference_config.eos_token_id)
            if inference_config.pad_token_id is not None:
                pad = torch.full_like(next_token, int(inference_config.pad_token_id))
                next_token = torch.where(finished.unsqueeze(1), pad, next_token)
            finished = finished | next_token.squeeze(1).eq(eos)

        sequences = torch.cat([sequences, next_token], dim=1)
        if bool(finished.all().item()):
            break

        step_start = now()
        decoded = decode_step(
            model,
            input_ids_t=next_token,
            cache=cache,
            inference_config=inference_config,
            return_aux=inference_config.use_mtp_draft or inference_config.return_cache_stats,
        )
        decode_time += now() - step_start
        cache = decoded["cache"]
        logits = decoded["logits"][:, -1, :]
        hidden_states = decoded.get("hidden_states")
        if inference_config.use_mtp_draft:
            mtp_drafts.append(mtp_draft_from_hidden(model, hidden_states, inference_config))

    end = now()
    num_generated = int(sequences.shape[1] - prompt_len)
    output = {
        "sequences": sequences,
        "scores": scores if inference_config.return_cache_stats else None,
        "cache": cache,
        "cache_stats": cache_summary(cache) if inference_config.return_cache_stats else None,
        "num_generated_tokens": num_generated,
        "prompt_length": prompt_len,
        "prefill_time": prefill_end - prefill_start,
        "decode_time": decode_time,
        "decode_time_per_token": decode_time / max(num_generated, 1),
        "speed": generation_speed_metrics(start, end, num_generated),
        "mtp_drafts": mtp_drafts if inference_config.use_mtp_draft else None,
    }

    if was_training:
        model.train()

    if return_dict:
        return output
    return sequences


@torch.no_grad()
def inference_autoregresive(
    model: torch.nn.Module,
    prompt: str | list[int] | torch.Tensor,
    tokenizer: Optional[Any] = None,
    **generation_kwargs,
) -> dict[str, Any]:
    config = InferenceConfig(**generation_kwargs)
    input_ids = encode_prompt(prompt, tokenizer=tokenizer)
    output = generate(
        model=model,
        input_ids=input_ids,
        inference_config=config,
        return_dict=True,
    )
    output["text"] = decode_token_ids(output["sequences"], tokenizer=tokenizer)
    return output


inference_autoregressive = inference_autoregresive


# ==============================================================================
# inference/audit.py
# ==============================================================================

from typing import Any, Optional

import torch



@torch.no_grad()
def audit_inference_pipeline(
    model: torch.nn.Module,
    prompt: str | list[int] | torch.Tensor,
    tokenizer: Optional[Any] = None,
    compare_logits: bool = True,
    **generation_kwargs,
) -> dict[str, Any]:
    config = InferenceConfig(return_cache_stats=True, **generation_kwargs)
    input_ids = encode_prompt(prompt, tokenizer=tokenizer)

    generation = generate(
        model=model,
        input_ids=input_ids,
        inference_config=config,
        return_dict=True,
    )

    comparison = None
    if compare_logits and input_ids.shape[1] > 0:
        comparison = compare_full_vs_cached_logits(
            model=model,
            input_ids=input_ids.to(generation["sequences"].device),
            inference_config=config,
        )

    return {
        "input_ids": input_ids,
        "sequences": generation["sequences"],
        "text": decode_token_ids(generation["sequences"], tokenizer=tokenizer),
        "generation": generation,
        "cache_stats": generation.get("cache_stats"),
        "full_vs_cached": comparison,
        "config": config,
    }
